#!/bin/bash

# install NPM
# run: cd static && npm install && npm install -g polymer-cli

cd static && npm run build:static && cd ..
go build
./CSGY9223-Final web restart -H 0.0.0.0 &
sleep 5 && ./warmup
