#!/bin/bash

# install NPM
# run: cd static && npm install && npm install -g polymer-cli

cd static && npm run build:static && cd ..

./CSGY9223-Final user restart -H 0.0.0.0 &
./CSGY9223-Final auth restart -H 0.0.0.0 &
./CSGY9223-Final feed restart -H 0.0.0.0 &
./CSGY9223-Final post restart -H 0.0.0.0 &
./CSGY9223-Final follow restart -H 0.0.0.0 &
./CSGY9223-Final web restart -H 0.0.0.0 &

until $(curl -s http://localhost:8080/ >> /dev/null); do
    echo "Waiting for web server to start..."
done

./warmup
