#!/bin/bash

curl -vvv localhost:8080/register -d username=mds796&password=1&password2=1
curl -vvv localhost:8080/register -d username=mvp307&password=1&password2=1
curl -vvv localhost:8080/register -d username=mks629&password=1&password2=1
