// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package followpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FollowRequest struct {
	FollowerUser         *User    `protobuf:"bytes,1,opt,name=FollowerUser,proto3" json:"FollowerUser,omitempty"`
	FollowedUser         *User    `protobuf:"bytes,2,opt,name=FollowedUser,proto3" json:"FollowedUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowRequest) Reset()         { *m = FollowRequest{} }
func (m *FollowRequest) String() string { return proto.CompactTextString(m) }
func (*FollowRequest) ProtoMessage()    {}
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *FollowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowRequest.Unmarshal(m, b)
}
func (m *FollowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowRequest.Marshal(b, m, deterministic)
}
func (m *FollowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowRequest.Merge(m, src)
}
func (m *FollowRequest) XXX_Size() int {
	return xxx_messageInfo_FollowRequest.Size(m)
}
func (m *FollowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowRequest proto.InternalMessageInfo

func (m *FollowRequest) GetFollowerUser() *User {
	if m != nil {
		return m.FollowerUser
	}
	return nil
}

func (m *FollowRequest) GetFollowedUser() *User {
	if m != nil {
		return m.FollowedUser
	}
	return nil
}

type FollowResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowResponse) Reset()         { *m = FollowResponse{} }
func (m *FollowResponse) String() string { return proto.CompactTextString(m) }
func (*FollowResponse) ProtoMessage()    {}
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *FollowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowResponse.Unmarshal(m, b)
}
func (m *FollowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowResponse.Marshal(b, m, deterministic)
}
func (m *FollowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowResponse.Merge(m, src)
}
func (m *FollowResponse) XXX_Size() int {
	return xxx_messageInfo_FollowResponse.Size(m)
}
func (m *FollowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FollowResponse proto.InternalMessageInfo

type UnfollowRequest struct {
	FollowerUser         *User    `protobuf:"bytes,1,opt,name=FollowerUser,proto3" json:"FollowerUser,omitempty"`
	FollowedUser         *User    `protobuf:"bytes,2,opt,name=FollowedUser,proto3" json:"FollowedUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnfollowRequest) Reset()         { *m = UnfollowRequest{} }
func (m *UnfollowRequest) String() string { return proto.CompactTextString(m) }
func (*UnfollowRequest) ProtoMessage()    {}
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *UnfollowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnfollowRequest.Unmarshal(m, b)
}
func (m *UnfollowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnfollowRequest.Marshal(b, m, deterministic)
}
func (m *UnfollowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnfollowRequest.Merge(m, src)
}
func (m *UnfollowRequest) XXX_Size() int {
	return xxx_messageInfo_UnfollowRequest.Size(m)
}
func (m *UnfollowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnfollowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnfollowRequest proto.InternalMessageInfo

func (m *UnfollowRequest) GetFollowerUser() *User {
	if m != nil {
		return m.FollowerUser
	}
	return nil
}

func (m *UnfollowRequest) GetFollowedUser() *User {
	if m != nil {
		return m.FollowedUser
	}
	return nil
}

type UnfollowResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnfollowResponse) Reset()         { *m = UnfollowResponse{} }
func (m *UnfollowResponse) String() string { return proto.CompactTextString(m) }
func (*UnfollowResponse) ProtoMessage()    {}
func (*UnfollowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *UnfollowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnfollowResponse.Unmarshal(m, b)
}
func (m *UnfollowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnfollowResponse.Marshal(b, m, deterministic)
}
func (m *UnfollowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnfollowResponse.Merge(m, src)
}
func (m *UnfollowResponse) XXX_Size() int {
	return xxx_messageInfo_UnfollowResponse.Size(m)
}
func (m *UnfollowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnfollowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnfollowResponse proto.InternalMessageInfo

type ViewRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewRequest) Reset()         { *m = ViewRequest{} }
func (m *ViewRequest) String() string { return proto.CompactTextString(m) }
func (*ViewRequest) ProtoMessage()    {}
func (*ViewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *ViewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewRequest.Unmarshal(m, b)
}
func (m *ViewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewRequest.Marshal(b, m, deterministic)
}
func (m *ViewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewRequest.Merge(m, src)
}
func (m *ViewRequest) XXX_Size() int {
	return xxx_messageInfo_ViewRequest.Size(m)
}
func (m *ViewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ViewRequest proto.InternalMessageInfo

func (m *ViewRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ViewResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewResponse) Reset()         { *m = ViewResponse{} }
func (m *ViewResponse) String() string { return proto.CompactTextString(m) }
func (*ViewResponse) ProtoMessage()    {}
func (*ViewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *ViewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewResponse.Unmarshal(m, b)
}
func (m *ViewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewResponse.Marshal(b, m, deterministic)
}
func (m *ViewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewResponse.Merge(m, src)
}
func (m *ViewResponse) XXX_Size() int {
	return xxx_messageInfo_ViewResponse.Size(m)
}
func (m *ViewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ViewResponse proto.InternalMessageInfo

func (m *ViewResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type SearchRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=Query,proto3" json:"Query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type SearchResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*FollowRequest)(nil), "follow.service.FollowRequest")
	proto.RegisterType((*FollowResponse)(nil), "follow.service.FollowResponse")
	proto.RegisterType((*UnfollowRequest)(nil), "follow.service.UnfollowRequest")
	proto.RegisterType((*UnfollowResponse)(nil), "follow.service.UnfollowResponse")
	proto.RegisterType((*ViewRequest)(nil), "follow.service.ViewRequest")
	proto.RegisterType((*ViewResponse)(nil), "follow.service.ViewResponse")
	proto.RegisterType((*SearchRequest)(nil), "follow.service.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "follow.service.SearchResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4b, 0xcb, 0xcf, 0xc9, 0xc9,
	0x2f, 0xd7, 0x83, 0x8a, 0x4a, 0xf1, 0x40, 0xf9, 0x60, 0x59, 0xa5, 0x7a, 0x2e, 0x5e, 0x37, 0x30,
	0x3f, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0xc8, 0x8c, 0x8b, 0x07, 0x22, 0x90, 0x5a, 0x14,
	0x5a, 0x9c, 0x5a, 0x24, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xa4, 0x07, 0xd5, 0x95, 0x9b,
	0x9f, 0x92, 0x9a, 0xa3, 0x07, 0x92, 0x09, 0x42, 0x51, 0x87, 0xa4, 0x2f, 0x05, 0xac, 0x8f, 0x89,
	0xa0, 0x3e, 0xb0, 0x3a, 0x25, 0x01, 0x2e, 0x3e, 0x98, 0x03, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53,
	0x95, 0x1a, 0x19, 0xb9, 0xf8, 0x43, 0xf3, 0xd2, 0x06, 0xd4, 0x55, 0x42, 0x5c, 0x02, 0x08, 0x27,
	0x40, 0xdd, 0x65, 0xca, 0xc5, 0x1d, 0x96, 0x99, 0x0a, 0x77, 0x92, 0x1a, 0x17, 0x0b, 0x01, 0xa7,
	0x80, 0xe5, 0x95, 0x2c, 0xb8, 0x78, 0x20, 0xda, 0x20, 0xc6, 0x08, 0x69, 0x70, 0xb1, 0x82, 0xc4,
	0x8b, 0x25, 0x18, 0x15, 0x98, 0x71, 0x68, 0x84, 0x28, 0x50, 0xf2, 0xe5, 0xe2, 0x0d, 0x4e, 0x4d,
	0x2c, 0x4a, 0xce, 0x20, 0xd1, 0x4a, 0x21, 0x11, 0x2e, 0xd6, 0xc0, 0xd2, 0xd4, 0xa2, 0x4a, 0xb0,
	0x77, 0x39, 0x83, 0x20, 0x1c, 0x25, 0x2b, 0x2e, 0x3e, 0x98, 0x71, 0xa4, 0x3a, 0xc5, 0x68, 0x0d,
	0x13, 0x17, 0x1b, 0x24, 0x80, 0x84, 0xdc, 0xe1, 0x2c, 0x59, 0x3d, 0xd4, 0xa4, 0xa5, 0x87, 0x92,
	0x92, 0xa4, 0xe4, 0x70, 0x49, 0x43, 0x6d, 0xf7, 0xe5, 0xe2, 0x80, 0x85, 0xb1, 0x90, 0x3c, 0xba,
	0x5a, 0xb4, 0x04, 0x20, 0xa5, 0x80, 0x5b, 0x01, 0xd4, 0x38, 0x47, 0x2e, 0x16, 0x50, 0x38, 0x0b,
	0x49, 0xa3, 0xab, 0x44, 0x8a, 0x34, 0x29, 0x19, 0xec, 0x92, 0x50, 0x23, 0xdc, 0xb9, 0xd8, 0x20,
	0x21, 0x84, 0xe9, 0x35, 0x94, 0x88, 0xc0, 0xf4, 0x1a, 0x6a, 0xc0, 0x3a, 0x71, 0x45, 0x71, 0x40,
	0x14, 0x14, 0x24, 0x25, 0xb1, 0x81, 0x33, 0x9a, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x77,
	0x53, 0x2b, 0x97, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FollowClient is the client API for Follow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FollowClient interface {
	Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error)
	Unfollow(ctx context.Context, in *UnfollowRequest, opts ...grpc.CallOption) (*UnfollowResponse, error)
	View(ctx context.Context, in *ViewRequest, opts ...grpc.CallOption) (*ViewResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type followClient struct {
	cc *grpc.ClientConn
}

func NewFollowClient(cc *grpc.ClientConn) FollowClient {
	return &followClient{cc}
}

func (c *followClient) Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error) {
	out := new(FollowResponse)
	err := c.cc.Invoke(ctx, "/follow.service.Follow/Follow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followClient) Unfollow(ctx context.Context, in *UnfollowRequest, opts ...grpc.CallOption) (*UnfollowResponse, error) {
	out := new(UnfollowResponse)
	err := c.cc.Invoke(ctx, "/follow.service.Follow/Unfollow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followClient) View(ctx context.Context, in *ViewRequest, opts ...grpc.CallOption) (*ViewResponse, error) {
	out := new(ViewResponse)
	err := c.cc.Invoke(ctx, "/follow.service.Follow/View", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/follow.service.Follow/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FollowServer is the server API for Follow service.
type FollowServer interface {
	Follow(context.Context, *FollowRequest) (*FollowResponse, error)
	Unfollow(context.Context, *UnfollowRequest) (*UnfollowResponse, error)
	View(context.Context, *ViewRequest) (*ViewResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterFollowServer(s *grpc.Server, srv FollowServer) {
	s.RegisterService(&_Follow_serviceDesc, srv)
}

func _Follow_Follow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServer).Follow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/follow.service.Follow/Follow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServer).Follow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Follow_Unfollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServer).Unfollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/follow.service.Follow/Unfollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServer).Unfollow(ctx, req.(*UnfollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Follow_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/follow.service.Follow/View",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServer).View(ctx, req.(*ViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Follow_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/follow.service.Follow/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Follow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "follow.service.Follow",
	HandlerType: (*FollowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Follow",
			Handler:    _Follow_Follow_Handler,
		},
		{
			MethodName: "Unfollow",
			Handler:    _Follow_Unfollow_Handler,
		},
		{
			MethodName: "View",
			Handler:    _Follow_View_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Follow_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
