// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package userpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CreateUserResponse struct {
	UID                  string   `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

type ViewUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	UID                  string   `protobuf:"bytes,2,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewUserRequest) Reset()         { *m = ViewUserRequest{} }
func (m *ViewUserRequest) String() string { return proto.CompactTextString(m) }
func (*ViewUserRequest) ProtoMessage()    {}
func (*ViewUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *ViewUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewUserRequest.Unmarshal(m, b)
}
func (m *ViewUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewUserRequest.Marshal(b, m, deterministic)
}
func (m *ViewUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewUserRequest.Merge(m, src)
}
func (m *ViewUserRequest) XXX_Size() int {
	return xxx_messageInfo_ViewUserRequest.Size(m)
}
func (m *ViewUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ViewUserRequest proto.InternalMessageInfo

func (m *ViewUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ViewUserRequest) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

type ViewUserResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	UID                  string   `protobuf:"bytes,2,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewUserResponse) Reset()         { *m = ViewUserResponse{} }
func (m *ViewUserResponse) String() string { return proto.CompactTextString(m) }
func (*ViewUserResponse) ProtoMessage()    {}
func (*ViewUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *ViewUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewUserResponse.Unmarshal(m, b)
}
func (m *ViewUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewUserResponse.Marshal(b, m, deterministic)
}
func (m *ViewUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewUserResponse.Merge(m, src)
}
func (m *ViewUserResponse) XXX_Size() int {
	return xxx_messageInfo_ViewUserResponse.Size(m)
}
func (m *ViewUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ViewUserResponse proto.InternalMessageInfo

func (m *ViewUserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ViewUserResponse) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

type SearchUserRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=Query,proto3" json:"Query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchUserRequest) Reset()         { *m = SearchUserRequest{} }
func (m *SearchUserRequest) String() string { return proto.CompactTextString(m) }
func (*SearchUserRequest) ProtoMessage()    {}
func (*SearchUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *SearchUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUserRequest.Unmarshal(m, b)
}
func (m *SearchUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUserRequest.Marshal(b, m, deterministic)
}
func (m *SearchUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUserRequest.Merge(m, src)
}
func (m *SearchUserRequest) XXX_Size() int {
	return xxx_messageInfo_SearchUserRequest.Size(m)
}
func (m *SearchUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUserRequest proto.InternalMessageInfo

func (m *SearchUserRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type SearchUserResponse struct {
	Usernames            []string `protobuf:"bytes,1,rep,name=Usernames,proto3" json:"Usernames,omitempty"`
	UIDs                 []string `protobuf:"bytes,2,rep,name=UIDs,proto3" json:"UIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchUserResponse) Reset()         { *m = SearchUserResponse{} }
func (m *SearchUserResponse) String() string { return proto.CompactTextString(m) }
func (*SearchUserResponse) ProtoMessage()    {}
func (*SearchUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *SearchUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUserResponse.Unmarshal(m, b)
}
func (m *SearchUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUserResponse.Marshal(b, m, deterministic)
}
func (m *SearchUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUserResponse.Merge(m, src)
}
func (m *SearchUserResponse) XXX_Size() int {
	return xxx_messageInfo_SearchUserResponse.Size(m)
}
func (m *SearchUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUserResponse proto.InternalMessageInfo

func (m *SearchUserResponse) GetUsernames() []string {
	if m != nil {
		return m.Usernames
	}
	return nil
}

func (m *SearchUserResponse) GetUIDs() []string {
	if m != nil {
		return m.UIDs
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "user.service.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "user.service.CreateUserResponse")
	proto.RegisterType((*ViewUserRequest)(nil), "user.service.ViewUserRequest")
	proto.RegisterType((*ViewUserResponse)(nil), "user.service.ViewUserResponse")
	proto.RegisterType((*SearchUserRequest)(nil), "user.service.SearchUserRequest")
	proto.RegisterType((*SearchUserResponse)(nil), "user.service.SearchUserResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x29, 0x2d, 0x4e, 0x2d, 0xd2,
	0x83, 0x8a, 0x29, 0xe9, 0x73, 0x09, 0x3a, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0x86, 0x16, 0xa7, 0x16,
	0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49, 0x71, 0x71, 0x80, 0xb8, 0x79, 0x89, 0xb9,
	0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0xbe, 0x92, 0x1a, 0x97, 0x10, 0xb2, 0x86,
	0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x01, 0x2e, 0xe6, 0x50, 0x4f, 0x17, 0xa8, 0x62, 0x10,
	0x53, 0xc9, 0x9e, 0x8b, 0x3f, 0x2c, 0x33, 0xb5, 0x9c, 0x48, 0x63, 0x61, 0x06, 0x30, 0x21, 0x0c,
	0x70, 0xe0, 0x12, 0x40, 0x18, 0x00, 0xb5, 0x86, 0x34, 0x13, 0x34, 0xb9, 0x04, 0x83, 0x53, 0x13,
	0x8b, 0x92, 0x33, 0x90, 0x1d, 0x21, 0xc2, 0xc5, 0x1a, 0x58, 0x9a, 0x5a, 0x54, 0x09, 0xd5, 0x0f,
	0xe1, 0x28, 0xb9, 0x71, 0x09, 0x21, 0x2b, 0x85, 0x5a, 0x27, 0xc3, 0xc5, 0x09, 0x33, 0xbe, 0x58,
	0x82, 0x51, 0x81, 0x59, 0x83, 0x33, 0x08, 0x21, 0x20, 0x24, 0xc4, 0xc5, 0x12, 0xea, 0xe9, 0x52,
	0x2c, 0xc1, 0x04, 0x96, 0x00, 0xb3, 0x8d, 0x9e, 0x33, 0x72, 0xb1, 0x80, 0x54, 0x08, 0x79, 0x73,
	0xb1, 0x41, 0x82, 0x49, 0x48, 0x5e, 0x0f, 0x39, 0xc0, 0xf5, 0x30, 0x42, 0x5b, 0x4a, 0x01, 0xb7,
	0x02, 0xa8, 0x3b, 0x5c, 0xb9, 0x58, 0x40, 0x41, 0x21, 0x24, 0x8b, 0xaa, 0x12, 0x2d, 0x7c, 0xa5,
	0xe4, 0x70, 0x49, 0x43, 0x8d, 0xf1, 0xe6, 0x62, 0x83, 0x78, 0x12, 0xdd, 0x4d, 0x18, 0xa1, 0x84,
	0xee, 0x26, 0xcc, 0xb0, 0x71, 0xe2, 0x88, 0x62, 0x03, 0x29, 0x29, 0x48, 0x4a, 0x62, 0x03, 0xa7,
	0x2b, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x7f, 0x7b, 0xe6, 0x68, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	View(ctx context.Context, in *ViewUserRequest, opts ...grpc.CallOption) (*ViewUserResponse, error)
	Search(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*SearchUserResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/user.service.User/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) View(ctx context.Context, in *ViewUserRequest, opts ...grpc.CallOption) (*ViewUserResponse, error) {
	out := new(ViewUserResponse)
	err := c.cc.Invoke(ctx, "/user.service.User/View", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Search(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*SearchUserResponse, error) {
	out := new(SearchUserResponse)
	err := c.cc.Invoke(ctx, "/user.service.User/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	Create(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	View(context.Context, *ViewUserRequest) (*ViewUserResponse, error)
	Search(context.Context, *SearchUserRequest) (*SearchUserResponse, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.service.User/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Create(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.service.User/View",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).View(ctx, req.(*ViewUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.service.User/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Search(ctx, req.(*SearchUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.service.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _User_Create_Handler,
		},
		{
			MethodName: "View",
			Handler:    _User_View_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _User_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
