// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package authpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterAuthRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAuthRequest) Reset()         { *m = RegisterAuthRequest{} }
func (m *RegisterAuthRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterAuthRequest) ProtoMessage()    {}
func (*RegisterAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *RegisterAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAuthRequest.Unmarshal(m, b)
}
func (m *RegisterAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAuthRequest.Marshal(b, m, deterministic)
}
func (m *RegisterAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAuthRequest.Merge(m, src)
}
func (m *RegisterAuthRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterAuthRequest.Size(m)
}
func (m *RegisterAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAuthRequest proto.InternalMessageInfo

func (m *RegisterAuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterAuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterAuthResponse struct {
	Cookie               string   `protobuf:"bytes,1,opt,name=Cookie,proto3" json:"Cookie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAuthResponse) Reset()         { *m = RegisterAuthResponse{} }
func (m *RegisterAuthResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterAuthResponse) ProtoMessage()    {}
func (*RegisterAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *RegisterAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAuthResponse.Unmarshal(m, b)
}
func (m *RegisterAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAuthResponse.Marshal(b, m, deterministic)
}
func (m *RegisterAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAuthResponse.Merge(m, src)
}
func (m *RegisterAuthResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterAuthResponse.Size(m)
}
func (m *RegisterAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAuthResponse proto.InternalMessageInfo

func (m *RegisterAuthResponse) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

type LoginAuthRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAuthRequest) Reset()         { *m = LoginAuthRequest{} }
func (m *LoginAuthRequest) String() string { return proto.CompactTextString(m) }
func (*LoginAuthRequest) ProtoMessage()    {}
func (*LoginAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *LoginAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAuthRequest.Unmarshal(m, b)
}
func (m *LoginAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAuthRequest.Marshal(b, m, deterministic)
}
func (m *LoginAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAuthRequest.Merge(m, src)
}
func (m *LoginAuthRequest) XXX_Size() int {
	return xxx_messageInfo_LoginAuthRequest.Size(m)
}
func (m *LoginAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAuthRequest proto.InternalMessageInfo

func (m *LoginAuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginAuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginAuthResponse struct {
	Cookie               string   `protobuf:"bytes,1,opt,name=Cookie,proto3" json:"Cookie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAuthResponse) Reset()         { *m = LoginAuthResponse{} }
func (m *LoginAuthResponse) String() string { return proto.CompactTextString(m) }
func (*LoginAuthResponse) ProtoMessage()    {}
func (*LoginAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *LoginAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAuthResponse.Unmarshal(m, b)
}
func (m *LoginAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAuthResponse.Marshal(b, m, deterministic)
}
func (m *LoginAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAuthResponse.Merge(m, src)
}
func (m *LoginAuthResponse) XXX_Size() int {
	return xxx_messageInfo_LoginAuthResponse.Size(m)
}
func (m *LoginAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAuthResponse proto.InternalMessageInfo

func (m *LoginAuthResponse) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

type VerifyAuthRequest struct {
	Cookie               string   `protobuf:"bytes,1,opt,name=Cookie,proto3" json:"Cookie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyAuthRequest) Reset()         { *m = VerifyAuthRequest{} }
func (m *VerifyAuthRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyAuthRequest) ProtoMessage()    {}
func (*VerifyAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *VerifyAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyAuthRequest.Unmarshal(m, b)
}
func (m *VerifyAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyAuthRequest.Marshal(b, m, deterministic)
}
func (m *VerifyAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyAuthRequest.Merge(m, src)
}
func (m *VerifyAuthRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyAuthRequest.Size(m)
}
func (m *VerifyAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyAuthRequest proto.InternalMessageInfo

func (m *VerifyAuthRequest) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

type VerifyAuthResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	UID                  string   `protobuf:"bytes,2,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyAuthResponse) Reset()         { *m = VerifyAuthResponse{} }
func (m *VerifyAuthResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyAuthResponse) ProtoMessage()    {}
func (*VerifyAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *VerifyAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyAuthResponse.Unmarshal(m, b)
}
func (m *VerifyAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyAuthResponse.Marshal(b, m, deterministic)
}
func (m *VerifyAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyAuthResponse.Merge(m, src)
}
func (m *VerifyAuthResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyAuthResponse.Size(m)
}
func (m *VerifyAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyAuthResponse proto.InternalMessageInfo

func (m *VerifyAuthResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerifyAuthResponse) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

type LogoutAuthRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Cookie               string   `protobuf:"bytes,2,opt,name=Cookie,proto3" json:"Cookie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutAuthRequest) Reset()         { *m = LogoutAuthRequest{} }
func (m *LogoutAuthRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutAuthRequest) ProtoMessage()    {}
func (*LogoutAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *LogoutAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutAuthRequest.Unmarshal(m, b)
}
func (m *LogoutAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutAuthRequest.Marshal(b, m, deterministic)
}
func (m *LogoutAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutAuthRequest.Merge(m, src)
}
func (m *LogoutAuthRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutAuthRequest.Size(m)
}
func (m *LogoutAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutAuthRequest proto.InternalMessageInfo

func (m *LogoutAuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LogoutAuthRequest) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

type LogoutAuthResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutAuthResponse) Reset()         { *m = LogoutAuthResponse{} }
func (m *LogoutAuthResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutAuthResponse) ProtoMessage()    {}
func (*LogoutAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *LogoutAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutAuthResponse.Unmarshal(m, b)
}
func (m *LogoutAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutAuthResponse.Marshal(b, m, deterministic)
}
func (m *LogoutAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutAuthResponse.Merge(m, src)
}
func (m *LogoutAuthResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutAuthResponse.Size(m)
}
func (m *LogoutAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutAuthResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RegisterAuthRequest)(nil), "auth.service.RegisterAuthRequest")
	proto.RegisterType((*RegisterAuthResponse)(nil), "auth.service.RegisterAuthResponse")
	proto.RegisterType((*LoginAuthRequest)(nil), "auth.service.LoginAuthRequest")
	proto.RegisterType((*LoginAuthResponse)(nil), "auth.service.LoginAuthResponse")
	proto.RegisterType((*VerifyAuthRequest)(nil), "auth.service.VerifyAuthRequest")
	proto.RegisterType((*VerifyAuthResponse)(nil), "auth.service.VerifyAuthResponse")
	proto.RegisterType((*LogoutAuthRequest)(nil), "auth.service.LogoutAuthRequest")
	proto.RegisterType((*LogoutAuthResponse)(nil), "auth.service.LogoutAuthResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x49, 0x2c, 0x2d, 0xc9, 0xd0,
	0x83, 0x8a, 0x29, 0xf9, 0x72, 0x09, 0x07, 0xa5, 0xa6, 0x67, 0x16, 0x97, 0xa4, 0x16, 0x39, 0x96,
	0x96, 0x64, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49, 0x71, 0x71, 0x84, 0x16, 0xa7,
	0x16, 0xe5, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xf9, 0x20, 0xb9,
	0x80, 0xc4, 0xe2, 0xe2, 0xf2, 0xfc, 0xa2, 0x14, 0x09, 0x26, 0x88, 0x1c, 0x8c, 0xaf, 0xa4, 0xc7,
	0x25, 0x82, 0x6a, 0x5c, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x18, 0x17, 0x9b, 0x73, 0x7e,
	0x7e, 0x76, 0x26, 0xcc, 0x34, 0x28, 0x4f, 0xc9, 0x8b, 0x4b, 0xc0, 0x27, 0x3f, 0x3d, 0x33, 0x8f,
	0x1a, 0x76, 0x6b, 0x73, 0x09, 0x22, 0x99, 0x45, 0xc0, 0x62, 0x6d, 0x2e, 0xc1, 0xb0, 0xd4, 0xa2,
	0xcc, 0xb4, 0x4a, 0x64, 0x9b, 0x71, 0x29, 0x76, 0xe2, 0x12, 0x42, 0x56, 0x0c, 0x35, 0x1a, 0x9f,
	0x3b, 0x05, 0xb8, 0x98, 0x43, 0x3d, 0x5d, 0xa0, 0x4e, 0x04, 0x31, 0x95, 0xdc, 0xc1, 0xae, 0xcb,
	0x2f, 0x2d, 0x21, 0xd6, 0xab, 0x08, 0xc7, 0x30, 0xa1, 0x38, 0x46, 0x84, 0x4b, 0x08, 0xd9, 0x20,
	0x88, 0x63, 0x8c, 0xf6, 0x32, 0x71, 0xb1, 0x80, 0x04, 0x84, 0x02, 0xb9, 0x38, 0x60, 0x31, 0x20,
	0xa4, 0xa8, 0x87, 0x1c, 0xd7, 0x7a, 0x58, 0x22, 0x5a, 0x4a, 0x09, 0x9f, 0x12, 0xa8, 0x47, 0x3d,
	0xb8, 0x58, 0xc1, 0x01, 0x2b, 0x24, 0x87, 0xaa, 0x18, 0x3d, 0xe6, 0xa4, 0xe4, 0x71, 0xca, 0x43,
	0x4d, 0xf2, 0xe6, 0x62, 0x83, 0x04, 0xa4, 0x10, 0x9a, 0x52, 0x8c, 0xb8, 0x90, 0x52, 0xc0, 0xad,
	0x00, 0x61, 0x18, 0x24, 0x20, 0x84, 0x30, 0xed, 0x45, 0x0d, 0x67, 0x74, 0xc3, 0x30, 0xc3, 0xcf,
	0x89, 0x23, 0x8a, 0x0d, 0xa4, 0xa4, 0x20, 0x29, 0x89, 0x0d, 0x9c, 0x4d, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x42, 0xc2, 0xb8, 0xa2, 0x37, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	Register(ctx context.Context, in *RegisterAuthRequest, opts ...grpc.CallOption) (*RegisterAuthResponse, error)
	Login(ctx context.Context, in *LoginAuthRequest, opts ...grpc.CallOption) (*LoginAuthResponse, error)
	Verify(ctx context.Context, in *VerifyAuthRequest, opts ...grpc.CallOption) (*VerifyAuthResponse, error)
	Logout(ctx context.Context, in *LogoutAuthRequest, opts ...grpc.CallOption) (*LogoutAuthResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Register(ctx context.Context, in *RegisterAuthRequest, opts ...grpc.CallOption) (*RegisterAuthResponse, error) {
	out := new(RegisterAuthResponse)
	err := c.cc.Invoke(ctx, "/auth.service.Auth/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Login(ctx context.Context, in *LoginAuthRequest, opts ...grpc.CallOption) (*LoginAuthResponse, error) {
	out := new(LoginAuthResponse)
	err := c.cc.Invoke(ctx, "/auth.service.Auth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Verify(ctx context.Context, in *VerifyAuthRequest, opts ...grpc.CallOption) (*VerifyAuthResponse, error) {
	out := new(VerifyAuthResponse)
	err := c.cc.Invoke(ctx, "/auth.service.Auth/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Logout(ctx context.Context, in *LogoutAuthRequest, opts ...grpc.CallOption) (*LogoutAuthResponse, error) {
	out := new(LogoutAuthResponse)
	err := c.cc.Invoke(ctx, "/auth.service.Auth/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	Register(context.Context, *RegisterAuthRequest) (*RegisterAuthResponse, error)
	Login(context.Context, *LoginAuthRequest) (*LoginAuthResponse, error)
	Verify(context.Context, *VerifyAuthRequest) (*VerifyAuthResponse, error)
	Logout(context.Context, *LogoutAuthRequest) (*LogoutAuthResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.service.Auth/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Register(ctx, req.(*RegisterAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.service.Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.service.Auth/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Verify(ctx, req.(*VerifyAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.service.Auth/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Logout(ctx, req.(*LogoutAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.service.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Auth_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Auth_Verify_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Auth_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
