// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raftkv.proto

package raftkvpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogEntryType int32

const (
	LogEntryType_PUT LogEntryType = 0
	LogEntryType_DEL LogEntryType = 1
)

var LogEntryType_name = map[int32]string{
	0: "PUT",
	1: "DEL",
}

var LogEntryType_value = map[string]int32{
	"PUT": 0,
	"DEL": 1,
}

func (x LogEntryType) String() string {
	return proto.EnumName(LogEntryType_name, int32(x))
}

func (LogEntryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0777dc47a482cc2, []int{0}
}

type LogEntry struct {
	Type                 LogEntryType `protobuf:"varint,1,opt,name=Type,proto3,enum=raftkv.model.LogEntryType" json:"Type,omitempty"`
	Key                  string       `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte       `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0777dc47a482cc2, []int{0}
}

func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetType() LogEntryType {
	if m != nil {
		return m.Type
	}
	return LogEntryType_PUT
}

func (m *LogEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *LogEntry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type KeyValue struct {
	KV                   map[string][]byte `protobuf:"bytes,1,rep,name=KV,proto3" json:"KV,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0777dc47a482cc2, []int{1}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKV() map[string][]byte {
	if m != nil {
		return m.KV
	}
	return nil
}

type Snapshot struct {
	Store                *KeyValue `protobuf:"bytes,1,opt,name=Store,proto3" json:"Store,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0777dc47a482cc2, []int{2}
}

func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snapshot.Unmarshal(m, b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return xxx_messageInfo_Snapshot.Size(m)
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetStore() *KeyValue {
	if m != nil {
		return m.Store
	}
	return nil
}

func init() {
	proto.RegisterEnum("raftkv.model.LogEntryType", LogEntryType_name, LogEntryType_value)
	proto.RegisterType((*LogEntry)(nil), "raftkv.model.LogEntry")
	proto.RegisterType((*KeyValue)(nil), "raftkv.model.KeyValue")
	proto.RegisterMapType((map[string][]byte)(nil), "raftkv.model.KeyValue.KVEntry")
	proto.RegisterType((*Snapshot)(nil), "raftkv.model.Snapshot")
}

func init() { proto.RegisterFile("raftkv.proto", fileDescriptor_e0777dc47a482cc2) }

var fileDescriptor_e0777dc47a482cc2 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0x4d, 0xea, 0x5c, 0xf7, 0xad, 0x48, 0x09, 0x22, 0x65, 0x07, 0x09, 0x3d, 0x15, 0x91,
	0x1c, 0x2a, 0xc2, 0xf0, 0x28, 0xee, 0x94, 0x1d, 0x24, 0x9b, 0x39, 0x78, 0x6b, 0x31, 0x2a, 0x6c,
	0x2e, 0x31, 0xc6, 0x41, 0xfe, 0x7b, 0x49, 0x62, 0x61, 0xc2, 0x6e, 0xef, 0xc1, 0x8f, 0xfc, 0xf2,
	0x3e, 0x28, 0x6c, 0xf7, 0xe6, 0x36, 0x7b, 0x66, 0xac, 0x76, 0x9a, 0x0c, 0xed, 0x53, 0xbf, 0xaa,
	0x6d, 0xdd, 0x43, 0xbe, 0xd4, 0xef, 0x8b, 0x9d, 0xb3, 0x9e, 0x30, 0x38, 0x5d, 0x7b, 0xa3, 0x2a,
	0x44, 0x51, 0x73, 0xde, 0xce, 0xd8, 0x21, 0xc8, 0x06, 0x2a, 0x10, 0x22, 0x72, 0xa4, 0x84, 0x8c,
	0x2b, 0x5f, 0x61, 0x8a, 0x9a, 0x89, 0x08, 0x91, 0x5c, 0xc0, 0x48, 0x76, 0xdb, 0x1f, 0x55, 0x65,
	0x14, 0x35, 0x85, 0x48, 0xa5, 0xfe, 0x82, 0x9c, 0x2b, 0x1f, 0x33, 0x61, 0x80, 0xb9, 0xac, 0x10,
	0xcd, 0x9a, 0x69, 0x7b, 0xf5, 0xdf, 0x30, 0x30, 0x8c, 0xcb, 0x68, 0x12, 0x98, 0xcb, 0xd9, 0x1d,
	0x8c, 0xff, 0x6a, 0xd0, 0x6d, 0x94, 0x8f, 0xbf, 0x9b, 0x88, 0x10, 0x83, 0x6e, 0x1f, 0x75, 0x38,
	0xe9, 0x62, 0xb9, 0xc7, 0x73, 0x54, 0xcf, 0x21, 0x5f, 0xed, 0x3a, 0xf3, 0xfd, 0xa1, 0x1d, 0xb9,
	0x81, 0xd1, 0xca, 0x69, 0x9b, 0x76, 0x4d, 0xdb, 0xcb, 0xe3, 0x56, 0x91, 0xa0, 0x6b, 0x0a, 0xc5,
	0xe1, 0x54, 0x32, 0x86, 0xec, 0xe9, 0x79, 0x5d, 0x9e, 0x84, 0xf0, 0xb8, 0x58, 0x96, 0xe8, 0x01,
	0x5e, 0xf2, 0xf4, 0x82, 0xe9, 0xfb, 0xb3, 0x78, 0xd3, 0xdb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x89, 0x15, 0xfc, 0xfe, 0x63, 0x01, 0x00, 0x00,
}
